name: integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: node:19-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./app
        run: npm install
      - name: Build
        working-directory: ./app
        run: npm run build

  unit-tests:
    runs-on: ubuntu-latest
    container: node:19-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./app
        run: npm install
      - name: Run tests
        working-directory: ./app
        run: npm test
